"""Calibration data loader.

Reads ``config/calibration.json`` (generated by
``scripts/calibration_report.py --output config/calibration.json``)
and returns the parsed dict.  If the file does not exist, returns
an empty dict — all consumers must treat missing keys as "use
hardcoded defaults".
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional

_CALIBRATION_PATH = Path(__file__).parent / "calibration.json"
_cache: Optional[Dict[str, Any]] = None


def load_calibration() -> Dict[str, Any]:
    """Load calibration data, caching after first read."""
    global _cache
    if _cache is not None:
        return _cache
    if _CALIBRATION_PATH.exists():
        _cache = json.loads(_CALIBRATION_PATH.read_text())
        return _cache
    return {}


def get_duration(
    jurisdiction: str,
    key: str,
    percentile: str = "p50",
) -> Optional[float]:
    """Convenience: get a calibrated duration value.

    Example::

        get_duration("hsr", "durations", "p75")
        get_duration("ec", "phase1_durations", "p50")
    """
    cal = load_calibration()
    section = cal.get(jurisdiction, {})
    dur = section.get(key, {})
    val = dur.get(percentile)
    return float(val) if val is not None else None


def get_rate(
    jurisdiction: str,
) -> Optional[float]:
    """Get the observed rate for a jurisdiction.

    Example::

        get_rate("samr")   # → 0.12 (SAMR activation rate)
        get_rate("cfius")  # → 0.04 (CFIUS review rate)
    """
    cal = load_calibration()
    section = cal.get(jurisdiction, {})
    rates = section.get("rates", {})
    return rates.get("observed")
